const cardsData = [
  {
    categoryName: 'christmas',
    words: [
      {
        en: 'snowman',
        ru: 'снеговик',
        image: './img/snowman.jpg',
        audio: './audio/snowman.wav',
      },
      {
        en: 'reindeer',
        ru: 'олень',
        image: './img/reindeer.jpg',
        audio: './audio/reindeer.wav',
      },
      {
        en: 'gift box',
        ru: 'подарок',
        image: './img/giftBox.jpg',
        audio: './audio/giftBox.wav',
      },
      {
        en: 'snowball',
        ru: 'снежок',
        image: './img/snowball.jpg',
        audio: './audio/snowball.wav',
      },
      {
        en: 'bauble',
        ru: 'шарик',
        image: './img/bauble.jpg',
        audio: './audio/bauble.wav',
      },
      {
        en: 'christmas sock',
        ru: 'новогодний носок',
        image: './img/christmasSock.jpg',
        audio: './audio/christmasSock.wav',
      },
      {
        en: 'christmas tree',
        ru: 'елка',
        image: './img/christmasTree.jpg',
        audio: './audio/christmasTree.wav',
      },
      {
        en: 'santa claus',
        ru: 'дед мороз',
        image: './img/santaClaus.jpg',
        audio: './audio/santaClaus.wav',
      },
    ],
    image: './img/christmas.jpg',
    audio: './audio/christmas.wav',
  },
  {
    categoryName: 'food',
    words: [
      {
        en: 'apple',
        ru: 'яблоко',
        image: './img/apple.jpg',
        audio: './audio/apple.wav',
      },
      {
        en: 'orange',
        ru: 'апельсин',
        image: './img/orange.jpg',
        audio: './audio/orange.wav',
      },
      {
        en: 'cucumber',
        ru: 'огурец',
        image: './img/cucumber.jpg',
        audio: './audio/cucumber.wav',
      },
      {
        en: 'tomato',
        ru: 'помидор',
        image: './img/tomato.jpg',
        audio: './audio/tomato.wav',
      },
      {
        en: 'soup',
        ru: 'суп',
        image: './img/soup.jpg',
        audio: './audio/soup.wav',
      },
      {
        en: 'pie',
        ru: 'пирог',
        image: './img/pie.jpg',
        audio: './audio/pie.wav',
      },
      {
        en: 'banana',
        ru: 'банан',
        image: './img/banana.jpg',
        audio: './audio/banana.wav',
      },
      {
        en: 'strawberry',
        ru: 'клубника',
        image: './img/strawberry.jpg',
        audio: './audio/strawberry.wav',
      },
    ],
    image: './img/food.jpg',
    audio: './audio/food.wav',
  },
  {
    categoryName: 'animals',
    words: [
      {
        en: 'cat',
        ru: 'кот',
        image: './img/cat.jpg',
        audio: './audio/cat.wav',
      },
      {
        en: 'dog',
        ru: 'собака',
        image: './img/dog.jpg',
        audio: './audio/dog.wav',
      },
      {
        en: 'cow',
        ru: 'корова',
        image: './img/cow.jpg',
        audio: './audio/cow.wav',
      },
      {
        en: 'tiger',
        ru: 'тигр',
        image: './img/tiger.jpg',
        audio: './audio/tiger.wav',
      },
      {
        en: 'elephant',
        ru: 'слон',
        image: './img/elephant.jpg',
        audio: './audio/elephant.wav',
      },
      {
        en: 'chicken',
        ru: 'курица',
        image: './img/chicken.jpg',
        audio: './audio/chicken.wav',
      },
      {
        en: 'fox',
        ru: 'лиса',
        image: './img/fox.jpg',
        audio: './audio/fox.wav',
      },
      {
        en: 'giraffe',
        ru: 'жираф',
        image: './img/giraffe.jpg',
        audio: './audio/giraffe.wav',
      },
    ],
    image: './img/animals.jpg',
    audio: './audio/animals.wav',
  },
  {
    categoryName: 'colors',
    words: [
      {
        en: 'white',
        ru: 'белый',
        image: './img/white.jpg',
        audio: './audio/white.wav',
      },
      {
        en: 'black',
        ru: 'черный',
        image: './img/black.jpg',
        audio: './audio/black.wav',
      },
      {
        en: 'blue',
        ru: 'синий',
        image: './img/blue.jpg',
        audio: './audio/blue.wav',
      },
      {
        en: 'green',
        ru: 'зеленый',
        image: './img/green.jpg',
        audio: './audio/green.wav',
      },
      {
        en: 'yellow',
        ru: 'желтый',
        image: './img/yellow.jpg',
        audio: './audio/yellow.wav',
      },
      {
        en: 'red',
        ru: 'красный',
        image: './img/red.jpg',
        audio: './audio/red.wav',
      },
      {
        en: 'purple',
        ru: 'фиолетовый',
        image: './img/purple.jpg',
        audio: './audio/purple.wav',
      },
      {
        en: 'grey',
        ru: 'серый',
        image: './img/grey.jpg',
        audio: './audio/grey.wav',
      },
    ],
    image: './img/colors.jpg',
    audio: './audio/colors.wav',
  },
  {
    categoryName: 'weather',
    words: [
      {
        en: 'sun',
        ru: 'солнце',
        image: './img/sun.jpg',
        audio: './audio/sun.wav',
      },
      {
        en: 'cloud',
        ru: 'облако',
        image: './img/cloud.jpg',
        audio: './audio/cloud.wav',
      },
      {
        en: 'snow',
        ru: 'снег',
        image: './img/snow.jpg',
        audio: './audio/snow.wav',
      },
      {
        en: 'rain',
        ru: 'дождь',
        image: './img/rain.jpg',
        audio: './audio/rain.wav',
      },
      {
        en: 'lightning',
        ru: 'молния',
        image: './img/lightning.jpg',
        audio: './audio/lightning.wav',
      },
      {
        en: 'ice',
        ru: 'лед',
        image: './img/ice.jpg',
        audio: './audio/ice.wav',
      },
      {
        en: 'fog',
        ru: 'туман',
        image: './img/fog.jpg',
        audio: './audio/fog.wav',
      },
      {
        en: 'wind',
        ru: 'ветер',
        image: './img/wind.jpg',
        audio: './audio/wind.wav',
      },
    ],
    image: './img/weather.jpg',
    audio: './audio/weather.wav',
  },
  {
    categoryName: 'numbers',
    words: [
      {
        en: 'zero',
        ru: 'ноль',
        image: './img/zero.jpg',
        audio: './audio/zero.wav',
      },
      {
        en: 'one',
        ru: 'один',
        image: './img/one.jpg',
        audio: './audio/one.wav',
      },
      {
        en: 'two',
        ru: 'два',
        image: './img/two.jpg',
        audio: './audio/two.wav',
      },
      {
        en: 'three',
        ru: 'три',
        image: './img/three.jpg',
        audio: './audio/three.wav',
      },
      {
        en: 'four',
        ru: 'четыре',
        image: './img/four.jpg',
        audio: './audio/four.wav',
      },
      {
        en: 'five',
        ru: 'пять',
        image: './img/five.jpg',
        audio: './audio/five.wav',
      },
      {
        en: 'six',
        ru: 'шесть',
        image: './img/six.jpg',
        audio: './audio/six.wav',
      },
      {
        en: 'seven',
        ru: 'семь',
        image: './img/seven.jpg',
        audio: './audio/seven.wav',
      },
      {
        en: 'eight',
        ru: 'восемь',
        image: './img/eight.jpg',
        audio: './audio/eight.wav',
      },
      {
        en: 'nine',
        ru: 'девять',
        image: './img/nine.jpg',
        audio: './audio/nine.wav',
      },
      {
        en: 'ten',
        ru: 'десять',
        image: './img/ten.jpg',
        audio: './audio/ten.wav',
      },
    ],
    image: './img/numbers.jpg',
    audio: './audio/numbers.wav',
  },
  {
    categoryName: 'emotions',
    words: [
      {
        en: 'happy',
        ru: 'счастливый',
        image: './img/happy.jpg',
        audio: './audio/happy.wav',
      },
      {
        en: 'sad',
        ru: 'грустный',
        image: './img/sad.jpg',
        audio: './audio/sad.wav',
      },
      {
        en: 'bored',
        ru: 'скучающий',
        image: './img/bored.jpg',
        audio: './audio/bored.wav',
      },
      {
        en: 'funny',
        ru: 'веселый',
        image: './img/funny.jpg',
        audio: './audio/funny.wav',
      },
      {
        en: 'cry',
        ru: 'плакать',
        image: './img/cry.jpg',
        audio: './audio/cry.wav',
      },
      {
        en: 'angry',
        ru: 'злой',
        image: './img/angry.jpg',
        audio: './audio/angry.wav',
      },
      {
        en: 'scared',
        ru: 'напуганный',
        image: './img/scared.jpg',
        audio: './audio/scared.wav',
      },
      {
        en: 'surprised',
        ru: 'удивленный',
        image: './img/surprised.jpg',
        audio: './audio/surprised.wav',
      },
    ],
    image: './img/emotions.jpg',
    audio: './audio/emotions.wav',
  },
  {
    categoryName: 'clothes',
    words: [
      {
        en: 't-shirt',
        ru: 'футболка',
        image: './img/t-shirt.jpg',
        audio: './audio/t-shirt.wav',
      },
      {
        en: 'socks',
        ru: 'носки',
        image: './img/socks.jpg',
        audio: './audio/socks.wav',
      },
      {
        en: 'shoes',
        ru: 'туфли',
        image: './img/shoes.jpg',
        audio: './audio/shoes.wav',
      },
      {
        en: 'dress',
        ru: 'платье',
        image: './img/dress.jpg',
        audio: './audio/dress.wav',
      },
      {
        en: 'skirt',
        ru: 'юбка',
        image: './img/skirt.jpg',
        audio: './audio/skirt.wav',
      },
      {
        en: 'coat',
        ru: 'пальто',
        image: './img/coat.jpg',
        audio: './audio/coat.wav',
      },
      {
        en: 'trousers',
        ru: 'брюки',
        image: './img/trousers.jpg',
        audio: './audio/trousers.wav',
      },
      {
        en: 'pyjamas',
        ru: 'пижама',
        image: './img/pyjamas.jpg',
        audio: './audio/pyjamas.wav',
      },
    ],
    image: './img/clothes.jpg',
    audio: './audio/clothes.wav',
  },
];

export default cardsData;
